### ISSUE TITLE
Error when replying to topic

### ISSUE THREAD

**Issue by xaoseric** [mybb/mybb2#189]
When you reply to a topic, this is what happens, looks like it is using post instead of get for quickreply
[![https://gyazo.com/3e868d46efad3ad0f6f7c6a04a1f80a0](https://i.gyazo.com/3e868d46efad3ad0f6f7c6a04a1f80a0.gif)](https://gyazo.com/3e868d46efad3ad0f6f7c6a04a1f80a0)

**Comment by euantorano** [comment]
Actually, this looks to be an issue with the change I made to routes. The route should be `topic/1/my-topic/reply`, but the view uses an array to build the URL rather than a set, leading the parameters to be the wrong way around - see #184.

Should be an easy fix, with @Nik101010 already working on it (though I might beat him to it for this one) :smile:

**Comment by Nik101010** [comment]
@euantorano links are done, forms are missing ^^ so yes, working on it :joy: 
Now I have to resolve conflicts on my branch *slapsEuantoranoBack* :stuck_out_tongue:
