### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by chack1172** [mybb/mybb2#219]
Hi, I installed this developement repositories in my pc and it works.
I copied the files in an hosting and I get this error:
Whoops, looks like something went wrong.

How to solve?

**Comment by euantorano** [comment]
Hi,

You need to make sure debug mode is enabled in the .env file or check your error log to see what the actual error is.

**Comment by chack1172** [comment]
This is my .env file. Do I have to edit APP_ENV?

APP_ENV=local
APP_DEBUG=true
APP_KEY=DW4VX7c0BN99e3L7AzGTBA2DOsbOYAfx

DB_HOST=localhost
DB_DATABASE=mybb2
DB_USERNAME=
DB_PASSWORD=my_mybb2

CACHE_DRIVER=file
SESSION_DRIVER=file

**Comment by chack1172** [comment]
Now it works
I had to edit file config/database.php and change
env('DB_DATABASE', 'forge')
in
env('DB_DATABASE', 'my_mybb2')

**Comment by euantorano** [comment]
Hi, yeah until we write an installer, you have to modify that file.

**Comment by JoshHarmon** [comment]
@chack1172 Don't edit the config/database.php file because you'll always have to exclude it from git stuff. The right thing to do to get what you want is change DB_DATABASE in the .env file.

env() checks if the first thing is defined in the .env file, and if not, falls back to the second parameter's value.

**Comment by chack1172** [comment]
I changed it but it tryed to conneto to database forge
